name: Auto Football Shorts Bot

on:
  schedule:
    - cron: '0 7 * * *' # Berjalan otomatis setiap hari pukul 14.00 WIB / 15.00 WITA
  workflow_dispatch: # Memungkinkan tombol run manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot Script
        run: |
          python bot.py
          
      - name: Simpan Hasil Video (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: video-shorts-hasil
          path: output.mp4
